// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VibraMonitor.Api.Data;

#nullable disable

namespace VibraMonitor.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VibraMonitor.Api.Models.VibrationReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("AccelX")
                        .HasColumnType("double precision");

                    b.Property<double?>("AccelY")
                        .HasColumnType("double precision");

                    b.Property<double?>("AccelZ")
                        .HasColumnType("double precision");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("Harmonic1st")
                        .HasColumnType("double precision");

                    b.Property<double>("Harmonic2nd")
                        .HasColumnType("double precision");

                    b.Property<double>("Harmonic3rd")
                        .HasColumnType("double precision");

                    b.Property<double>("Harmonic4th")
                        .HasColumnType("double precision");

                    b.Property<double>("HarmonicDc")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsAnomaly")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("DeviceId", "Timestamp");

                    b.ToTable("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
